controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    both_arms_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_gripper_controller:
      type: position_controllers/GripperActionController

    right_gripper_controller:
      type: position_controllers/GripperActionController

left_arm_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

right_arm_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

both_arms_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

left_gripper_controller:
  ros__parameters:
    use_sim_time: true
    joint: left_gripper_left_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

right_gripper_controller:
  ros__parameters:
    use_sim_time: true
    joint: right_gripper_left_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
